# Exercici 1
## Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import pandas as pd

In [41]:
def datos_stat(arr):
    if arr.ndim > 1:
        print("El array es multidimensional")
        return
    else:
        s = pd.Series(arr)
        resumen = s.describe()
        return resumen

In [42]:
import numpy as np

In [43]:
from numpy import random

In [49]:
A = random.randint(20, size=(10))
B = random.randint(20, size=(2,3))
print("A=", A)
print("B=", B)

A= [15 16  9 17  4 19  0 12 13  2]
B= [[ 8 12  2]
 [ 7 11  3]]


In [50]:
datos_stat(A)

count    10.0000
mean     10.7000
std       6.6675
min       0.0000
25%       5.2500
50%      12.5000
75%      15.7500
max      19.0000
dtype: float64

In [51]:
datos_stat(B)

El array es multidimensional


# Exercici 2
## Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [77]:
N = int(input("Qué dimension N quieres para hacer una tabla aleatoria NxN?"))
Tab1 = np.random.randint(100, size=(N,N))
Tab1

Qué dimension N quieres para hacer una tabla aleatoria NxN?5


array([[29, 27, 78, 86, 86],
       [50, 33, 18, 69, 91],
       [90, 26,  8, 62, 17],
       [88, 64, 41, 20, 78],
       [44, 26, 17, 29, 13]])

# Exercici 3
## Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

Aquí la función:

In [82]:
def totals(tabla):
    Txfila = np.sum(tabla, axis = 1)
    Txcol = np.sum(tabla, axis = 0)
    print("total por filas: ", Txfila)
    print("total por columnas: ", Txcol)

Lo compruebo sobre la tabla anterior NxN, ya que la tengo.

In [83]:
totals(Tab1)

total por filas:  [306 261 203 291 129]
total por columnas:  [301 176 162 266 285]


Y ahora hago una tabla NXM para comprobar que funciona tambien, preguntando para practicar:

In [84]:
N = int(input("Qué dimension N quieres para hacer una tabla aleatoria NxM?"))
M = int(input("Qué dimension M quieres para hacer una tabla aleatoria NxM?"))
Tab2 = np.random.randint(100, size=(N,M))
Tab2

Qué dimension N quieres para hacer una tabla aleatoria NxM?3
Qué dimension M quieres para hacer una tabla aleatoria NxM?5


array([[86, 43,  6, 30, 18],
       [ 0, 46, 13, 30, 88],
       [36, 44, 94, 77, 24]])

In [85]:
totals(Tab2)

total por filas:  [183 177 275]
total por columnas:  [122 133 113 137 130]


# Exercici 4
## Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

El coeficiente de correlación, establece cuan fuerte es la relación entre las variables de una tabla (entre -1 y +1), y si esa relación es directa (positiva), inversa (negativa), o nula (=0).

Debemos tener en cuneta que calcula el coeficiente de correlación de Pearson, es decir, que funciona si dicha correlación entre las variables tiende a ser lineal.

Dicho de otro modo, mide la tendencia al cambio de una variable cuando cambia otra sin tener en cuenta la causalidad y considernado que dicha tendencia es lineal.

Nota: Es bueno hacer el gráfico de dispersión para observar si hay datos fuera de rango (a ser eliminados) o si la relación no es lineal y requiere otro tipo de análisis de correlación más adecuado que el de Pearson.

La función de Pandas para ello es corr()

Si queremos hacerlo con una función programada, es decir, sin usar corr(), tenemos que tener en cuenta que su definición:


$$r=\frac{Covarianza(X,Y)}{Dev_{tipica}(X)Dev_{tipica}(Y)}=\frac{Covarianza(X,Y)}{\sqrt{Varianza(X))}\sqrt{Varianza(Y))}}$$

Es decir:

Definimos como Varinaza:
$${\sigma _{x}}^{2}=\frac{\sum {x_{i}}^{2}.f_{i}}{N}-\bar{X}^{2}$$
$${\sigma _{y}}^{2}=\frac{\sum {y_{i}}^{2}.f_{i}}{N}-\bar{Y}^{2}$$
Siendo la Desviación típica: ${\sigma _{x}}=\sqrt{{\sigma _{x}}^{2}}$; ${\sigma _{y}}=\sqrt{{\sigma _{y}}^{2}}$

Y la Covarianza:
$${\sigma _{xy}}=\frac{\sum {x_{i}.y_{i}}.f_{i}}{N}-\bar{X}.\bar{Y}$$

Donde $N=\sum f_{i}$, siendo por tanto:
- la cantidad de valores correspondientes a X o a Y, si son datos sin agrupar $(f_{i}=1)$
- la suma de las frecunecias de los valores si son datos agrupados $(f_{i}\neq 1)$

Calculando las medias como:
$$\bar{X}=\frac{\sum {x_{i}}.f_{i}}{N}$$
$$\bar{Y}=\frac{\sum {y_{i}}.f_{i}}{N}$$

La correlación se peude definir tambien como:
$$r=\frac{\sum [(x_{i}-\bar{X}).(y_{i}-\bar{Y})]}{\sqrt{\sum (x_{i}-\bar{X})^{2}}.{\sqrt{\sum (y_{i}-\bar{Y})^{2}}}}$$

## 1) Funcion pura de cálculo de r en datos sin agrupar

In [39]:
def calc_corr(X, Y):
    N = len(X)
    media_X = sum(X) / N
    media_Y = sum(Y) / N
    CovXY = sum((xi - media_X)*(yi - media_Y) for xi, yi in zip(X, Y))
    sdev1 = (sum((xi - media_X)**2 for xi in X))**0.5
    sdev2 = (sum((yi - media_Y)**2 for yi in Y))**0.5
    r = round(CovXY / (sdev1 * sdev2),2)
    return r

Vamos a hacer un ejemplo y su inverso para asegurar que es correcto:

In [40]:
X = list(range(1, 11))
Y = [2*x for x in X]
print ("X=",X)
print ("Y=",Y)

X= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Y= [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [41]:
print("El coef de correlación de Pearson entre X e Y es:",calc_corr(X,Y))

El coef de correlación de Pearson entre X e Y es: 1.0


In [42]:
X1 = list(range(1, 11))
Y1 = list(reversed([2*x for x in X1]))
print ("X1=",X1)
print ("Y1=",Y1)

X1= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Y1= [20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


In [43]:
print("El coef de correlación de Pearson entre X e Y es:",calc_corr(X1,Y1))

El coef de correlación de Pearson entre X e Y es: -1.0


## 2) hagámoslo con corr()
Convertiremos primero las listas en un Dataframe, y luego aplicamos la función de pandas:

In [44]:
import pandas as pd

In [45]:
df = pd.DataFrame({"X" : X, "Y" :Y})
r1 = df["X"].corr(df["Y"]).round(2)
print("El coef de correlación de Pearson entre X e Y es:", r1)

El coef de correlación de Pearson entre X e Y es: 1.0


In [46]:
df = pd.DataFrame({"X1" : X1, "Y1" :Y1})
r1 = df["X1"].corr(df["Y1"]).round(2)
print("El coef de correlación de Pearson entre X1 e Y1 es:", r1)

El coef de correlación de Pearson entre X1 e Y1 es: -1.0


## 3) Cuando las columnas representan los datos, y las filas las frecuencia, tenemos que crear una matriz de correlación
Primero creamos la matriz, luego la convertimos en un dataframe de pandas y luego aplicamos la función:

In [56]:
import pandas as pd
datos = {'Ana': [5, 8, 7, 10], 'Juan': [6, 9, 5, 3], 'María': [7, 8, 9, 10]}
df = pd.DataFrame(datos)
print(df)

   Ana  Juan  María
0    5     6      7
1    8     9      8
2    7     5      9
3   10     3     10


In [57]:
r2 = df.corr()
print(r2)

            Ana      Juan     María
Ana    1.000000 -0.352282  0.868243
Juan  -0.352282  1.000000 -0.671317
María  0.868243 -0.671317  1.000000
